# Generated by Django 3.0.3 on 2020-02-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppKesh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dailyTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('customer_name', models.CharField(max_length=200)),
                ('charge', models.IntegerField()),
                ('Paid_amount', models.IntegerField()),
                ('return_amount', models.IntegerField()),
                ('total_amount', models.IntegerField()),
            ],
        ),
    ]
