# Generated by Django 3.0.3 on 2020-02-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppKesh', '0002_dailytransactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='productadding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.ImageField(default=0, upload_to='')),
                ('product_Image', models.ImageField(blank=True, upload_to='media/productImage')),
            ],
        ),
    ]
