# Generated by Django 3.0.3 on 2020-02-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppKesh', '0004_auto_20200219_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productadding',
            name='product_Image',
            field=models.ImageField(blank=True, upload_to='media/productImage/'),
        ),
    ]
