# Generated by Django 3.0.3 on 2020-02-20 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppKesh', '0007_expenses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='expenses',
            new_name='expensesM',
        ),
    ]
