# Generated by Django 3.0.3 on 2020-02-20 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppKesh', '0008_auto_20200220_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensesm',
            name='date_of_expenses',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
