# Generated by Django 3.0.3 on 2020-02-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppKesh', '0009_expensesm_date_of_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytransactions',
            name='staffName',
            field=models.CharField(choices=[('Staff-1', 'One'), ('Staff-2', 'Two'), ('Staff-3', 'Three'), ('Owner', 'Owner')], default=1, max_length=200),
            preserve_default=False,
        ),
    ]
