# Generated by Django 3.0.3 on 2020-07-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppKesh', '0010_dailytransactions_staffname'),
    ]

    operations = [
        migrations.CreateModel(
            name='stafflist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffname', models.CharField(max_length=200)),
                ('staffemail', models.EmailField(max_length=200)),
                ('staffnumber', models.IntegerField()),
                ('staffpassword', models.CharField(max_length=200)),
            ],
        ),
    ]
